version: "3.9"

services:
  loccar-locadora:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loccar-locadora-auth
    ports:
      - "5002:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=loccardb_locadora;Username=postgres;Password=postgres
    # depends_on:
    #   - db

  # db:
  #   image: postgres:16
  #   container_name: postgres-locadora-auth
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: loccardb_auth
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
